config/routes.rb
MyCollection::Application.routes.draw do

  resources :categories

  resources :items do
    resources :comments
    post 'search', :on => :collection
  end

  root to: 'main_pages#home'
  match '/about', to: 'main_pages#about'
  match '/contact', to: 'main_pages#contact'
  match '/help', to: 'main_pages#help'
  
  resources :users
  match '/signup', to: 'users#new'
  match '/login', to: 'users#login'
  match '/logout', to: 'users#logout'
  match '/my_account', to: 'users#my_account'
  resources :users do
    post 'process_login', on: :collection
  end
  

end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController
end

app/helpers/main_pages_helper.rb
module MainPagesHelper
end

app/views/main_pages/about.html.erb
<%= provide(:page_title, 'About') %>
<h1>About</h1>
<p>This page has been created for the WAD Rails Assessment in December 2012.</p>

app/views/main_pages/contact.html.erb
<%= provide(:page_title, 'Contact') %>
<h1>Contact</h1>
<p>
  You can e-mail me: g.muszynski.12@aberdeen.ac.uk or visit
  <%= link_to 'Aberdeen University', 'http://www.abdn.ac.uk' %>.
</p>

app/views/main_pages/help.html.erb
<%= provide(:page_title, 'Help') %>
<h1>Help</h1>
<p>
  Here you can find help with your problems on this web page and learn about
  it a bit more.
</p>

app/views/main_pages/home.html.erb
<%= provide(:page_title, 'Home') %>
<h1>Welcome to My Collection!</h1>
<h2>On this page you can find my personal favourites. Have a look around!</h2>
<p>
  Click <%= link_to 'here', items_path  %> to see the list of all the items in this collection.
</p>
<p>
  Click <%= link_to 'here', categories_path  %> to see the catagories available.
</p>
<p>
  If you don't have your account, create it <%= link_to 'here', signup_path %>.
</p>