config/routes.rb
MyCollection::Application.routes.draw do

  resources :categories

  resources :items do
    resources :comments
    post 'search', :on => :collection
  end

  root to: 'main_pages#home'
  match '/about', to: 'main_pages#about'
  match '/contact', to: 'main_pages#contact'
  match '/help', to: 'main_pages#help'
  
  resources :users
  match '/signup', to: 'users#new'
  match '/login', to: 'users#login'
  match '/logout', to: 'users#logout'
  match '/my_account', to: 'users#my_account'
  resources :users do
    post 'process_login', on: :collection
  end
  

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :description, :title, :category_id, :subcategory
  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true
  validates :subcategory, presence: true, length: { maximum: 20 }
  has_many :comments  
  belongs_to :category
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :login_required, only: [:new, :edit, :create, :update, :destroy]
  before_filter :permission_required, only: [:new, :edit, :create, :update, :destroy]
  
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
    @categories = Category.find(:all)
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
  
  def search
    @item = Item.find_by_title("%#{params[:key]}%")
    redirect_to
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
    <div class="field">
    <%= f.label :subcategory %><br />
    <%= f.text_field :subcategory %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%= provide(:page_title, 'Edit Item') %>
<h1>Edit</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %>
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= provide(:page_title, 'List View') %>
<h1>My Collection</h1>

<table align="center">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Category</th>
    <th>Subcategory</th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.title %></td>
    <td><%= item.description[0, 120] + '...' %></td>
    <td><%= item.category.name %></td>
    <td><%= item.subcategory %></td>
    <td><%= link_to 'More', item %></td>
  </tr>
<% end %>
</table>

<p><%= link_to 'New Item', new_item_path %></p>
<p><%= link_to 'Categories', categories_path %></p>

app/views/items/new.html.erb
<%= provide(:page_title, 'Add Item') %>
<h1>Add to Collection</h1>

<%= render 'form' %>

<%= link_to 'Back to Collection', items_path %>

app/views/items/search.html.erb
<html>
  <h1>Search results</h1>
  <table align="center">
    <tr>
      <th>Title</th>
    </tr>
    <% @item.each do |item| %>
    <tr>
      <td><% item.title %></td>
    </tr>
    <% end %>
  </table>
</html>

app/views/items/show.html.erb
<%= provide(:page_title, @item.title ) %>
<p id="notice"><%= notice %></p>

<h1>More about this item</h1>

<table align="center">
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= @item.title %></td>
    <td><%= @item.description %></td>
  </tr>  
</table>

<h3>
  This item belongs to the '<%= @item.category.name %>' category.<br> It is filed under
  '<%= @item.subcategory %>'.
</h3>

<p>
  <%= link_to 'Edit', edit_item_path(@item) %>
  <%= link_to 'Delete', @item, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

<p><%= link_to 'Back to the Collection', items_path %></p>

<h3>Add your comment</h3>
<%= form_for([@item, @item.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<table align="center">
  <tr>
    <th>Commenter</th>
    <th>Comment</th>
  </tr>
  <% @item.comments.each do |comment| %>
  <tr>
    <td><%= comment.commenter %></td>
    <td><%= comment.content %></td>
  </tr>
  <% end %>
</table>