config/routes.rb
MyCollection::Application.routes.draw do

  resources :categories

  resources :items do
    resources :comments
    post 'search', :on => :collection
  end

  root to: 'main_pages#home'
  match '/about', to: 'main_pages#about'
  match '/contact', to: 'main_pages#contact'
  match '/help', to: 'main_pages#help'
  
  resources :users
  match '/signup', to: 'users#new'
  match '/login', to: 'users#login'
  match '/logout', to: 'users#logout'
  match '/my_account', to: 'users#my_account'
  resources :users do
    post 'process_login', on: :collection
  end
  

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <ul>
    <li>Created by Grzegorz Muszynski</li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Contact', contact_path %></li>
  </ul>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Help', help_path %></li>
    <li><%= link_to 'Log In', login_path %></li>
    <li><%= link_to 'My Account', my_account_path %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Collection | <%= yield(:page_title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <% flash.each do |name,msg|%>
  <%= content_tag :div, msg, id: "flash#{name}" %>
  <% end %>

  <%= yield %>

  <%= render 'layouts/footer' %>

</body>
</html>